{
 "title": "Country Overview",
 "description": "Country Overview",
 "time": { "from": "now-30d", "to": "now+1d" },
 "templating": {
  "list": [
   {
    "name": "country",
    "label": "country",
    "query": "select distinct(country) from (select country, confirmed_cumulative from worldometers) ;"
   }
  ]
 },
 "panels": [
  {
   "title": "Detected",
   "type": "stat",
   "description": "Total detected",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "worldometers",
     "query": "SELECT \"confirmed_cumulative\" FROM \"worldometers\" WHERE (\"country\" =~ /^$country$/) ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "Quote / Detected",
   "type": "stat",
   "description": "Quote",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "worldometers",
     "query": "select sum(b) / sum(a) * 100 from (select a, b from (select sum(c) as a from (SELECT last(\"confirmed_cumulative\") as c FROM \"worldometers\" WHERE (\"country\" != 'None') GROUP BY \"country\" order by time desc LIMIT 1) order by time desc), (SELECT \"confirmed_cumulative\" as b FROM \"worldometers\" WHERE (\"country\" =~ /^$country$/) ORDER BY time DESC LIMIT 1) order by time desc) order by time desc;",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "Deaths",
   "type": "stat",
   "description": "Deaths \\ Contagions * 100",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "worldometers",
     "query": "SELECT \"death_cumulative\" FROM \"worldometers\" WHERE (\"country\" =~ /^$country$/) ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "Deaths",
   "type": "stat",
   "description": "Deaths \\ Contagions * 100",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "worldometers",
     "query": "SELECT 100*\"death_cumulative\" / \"confirmed_cumulative\" FROM \"worldometers\" WHERE (\"country\" =~ /^$country$/) ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "Recovered",
   "type": "stat",
   "description": "Deaths \\ Contagions * 100",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "worldometers",
     "query": "SELECT \"recovered_cumulative\" FROM \"worldometers\" WHERE (\"country\" =~ /^$country$/) ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "Recovered",
   "type": "stat",
   "description": "Deaths \\ Contagions * 100",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "worldometers",
     "query": "SELECT 100*\"recovered_cumulative\" / \"confirmed_cumulative\" FROM \"worldometers\" WHERE (\"country\" =~ /^$country$/) ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "Active",
   "type": "stat",
   "description": "Total detected",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "worldometers",
     "query": "SELECT \"confirmed_cumulative\" - \"death_cumulative\" - \"recovered_cumulative\" FROM \"worldometers\" WHERE (\"country\" =~ /^$country$/) ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "I.C.U.",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "worldometers",
     "query": "SELECT \"severe_cumulative\" FROM \"worldometers\" WHERE (\"country\" =~ /^$country$/) ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "I.C.U.",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "worldometers",
     "query": "select 100* mean(a) / mean(b) from (SELECT \"severe_cumulative\" as a FROM \"worldometers\" WHERE (\"country\" =~ /^$country$/) ORDER BY time DESC LIMIT 1), (SELECT (\"confirmed_cumulative\" - \"death_cumulative\" - \"recovered_cumulative\") as b FROM \"worldometers\" WHERE (\"country\" =~ /^$country$/) ORDER BY time DESC LIMIT 1) order by time desc;\n",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "Daily",
   "type": "graph",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "ICU",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "severe_diff" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "$country" }
     ]
    },
    {
     "alias": "Deaths",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "death_diff" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "$country" }
     ]
    }
   ]
  },
  {
   "title": "Recovered",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 11, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Recovered Total",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "recovered_cumulative" ], "type": "field" },
       { "params": [ "Severe" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "$country" }
     ]
    },
    {
     "alias": "Recovered Today",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "recovered_diff" ], "type": "field" },
       { "params": [ "Severe" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "$country" }
     ]
    }
   ]
  },
  {
   "title": "Deaths",
   "type": "graph",
   "gridPos": { "h": 12, "w": 7, "x": 17, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Death Total",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "death_cumulative" ], "type": "field" },
       { "params": [ "Severe" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "$country" }
     ]
    },
    {
     "alias": "Death Today",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "death_diff" ], "type": "field" },
       { "params": [ "Severe" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "$country" }
     ]
    }
   ]
  },
  {
   "title": "Data",
   "type": "table",
   "gridPos": { "h": 29, "w": 13, "x": 11, "y": 16 },
   "targets": [
    {
     "alias": "Confirmed Total",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       { "params": [ "Severe" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "$country" }
     ]
    },
    {
     "alias": "Confirmed Incr.",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "confirmed_diff" ], "type": "field" },
       { "params": [ "Severe" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "$country" }
     ]
    },
    {
     "alias": "Severe Active",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "severe_cumulative" ], "type": "field" },
       { "params": [ "Severe" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "$country" }
     ]
    },
    {
     "alias": "Severe Today",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "severe_diff" ], "type": "field" },
       { "params": [ "Severe" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "$country" }
     ]
    },
    {
     "alias": "Total Death",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "death_cumulative" ], "type": "field" },
       { "params": [ "Severe" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "$country" }
     ]
    },
    {
     "alias": "Death Today",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "death_diff" ], "type": "field" },
       { "params": [ "Severe" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "$country" }
     ]
    }
   ]
  },
  {
   "title": "Contagions w/ 3% CFR",
   "type": "graph",
   "description": "Projection w/ a 3% let.",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Confirmed Total",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       { "params": [ "Severe" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "$country" }
     ]
    },
    {
     "alias": "Confirmed Incr.",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "confirmed_diff" ], "type": "field" },
       { "params": [ "Severe" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "$country" }
     ]
    },
    {
     "alias": "Conf w/Let.3%",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "death_cumulative" ], "type": "field" },
       { "params": [ "*33.3" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "$country" }
     ]
    }
   ]
  },
  {
   "title": "Contagions w/ 1% CFR VS Detected",
   "type": "graph",
   "description": "Projection w/ a 3% let.",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Confirmed Total",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       { "params": [ "Severe" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "$country" }
     ]
    },
    {
     "alias": "Confirmed Incr.",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "confirmed_diff" ], "type": "field" },
       { "params": [ "Severe" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "$country" }
     ]
    },
    {
     "alias": "Conf w/Let.1%",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "death_cumulative" ], "type": "field" },
       { "params": [ "*100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "$country" }
     ]
    }
   ]
  },
  {
   "title": "Severe",
   "type": "graph",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Severe Total",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "severe_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "$country" }
     ]
    },
    {
     "alias": "Severe Today",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "severe_diff" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "$country" }
     ]
    },
    {
     "alias": "3% death rate to severes ~10%",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "death_cumulative" ], "type": "field" },
       { "params": [ "*33.3 * 0.03" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "$country" }
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 53 },
   "content": "<img src=\"//www.shinystat.com/cgi-bin/shinystat.cgi?USER=gdax\" alt=\"Users\" style=\"border:0px\" /></a>\n\n\n\n"
  }
 ]
}