{
 "title": "Covid19",
 "time": { "from": "now-24d", "to": "now+1d" },
 "panels": [
  {
   "title": "Europe vs Italy Lag vs China Lag",
   "type": "graph",
   "gridPos": { "h": 14, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "France",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "France" },
      { "condition": "AND", "key": "confirmed_diff", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "Italy -8 days",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       { "params": [ "shift_8_days" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Italy" },
      { "condition": "AND", "key": "confirmed_diff", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "Germany",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Germany" },
      { "condition": "AND", "key": "confirmed_diff", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "Spain",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Spain" },
      { "condition": "AND", "key": "confirmed_diff", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "China -46days",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "shift_46_days" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "China" },
      { "condition": "AND", "key": "confirmed_diff", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Contagions Active",
   "type": "graph",
   "gridPos": { "h": 12, "w": 10, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "World" }
   ],
   "targets": [
    {
     "alias": "Italy",
     "measurement": "summary_worldometers_country_86400",
     "query": "SELECT \"confirmed_cumulative\"  - \"death_cumulative\" - \"recovered_cumulative\" FROM \"summary_worldometers_country_86400\" WHERE (\"country\" = 'Italy') AND $timeFilter",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Italy" }
     ]
    },
    {
     "alias": "Spain",
     "measurement": "summary_worldometers_country_86400",
     "query": "SELECT \"confirmed_cumulative\"  - \"death_cumulative\" - \"recovered_cumulative\" FROM \"summary_worldometers_country_86400\" WHERE (\"country\" = 'Spain') AND $timeFilter",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Spain" }
     ]
    },
    {
     "alias": "France",
     "measurement": "summary_worldometers_country_86400",
     "query": "SELECT \"confirmed_cumulative\" FROM \"summary_worldometers_country_86400\" WHERE (\"country\" = 'France') AND $timeFilter",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "France" }
     ]
    },
    {
     "alias": "Germany",
     "measurement": "summary_worldometers_country_86400",
     "query": "SELECT \"confirmed_cumulative\"  - \"death_cumulative\" - \"recovered_cumulative\" FROM \"summary_worldometers_country_86400\" WHERE (\"country\" = 'Germany') AND $timeFilter",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Germany" }
     ]
    },
    {
     "alias": "USA",
     "measurement": "summary_worldometers_country_86400",
     "query": "SELECT \"confirmed_cumulative\"  - \"death_cumulative\" - \"recovered_cumulative\" FROM \"summary_worldometers_country_86400\" WHERE (\"country\" = 'USA') AND $timeFilter",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "USA" }
     ]
    },
    {
     "alias": "UK",
     "measurement": "summary_worldometers_country_86400",
     "query": "SELECT \"confirmed_cumulative\"  - \"death_cumulative\" - \"recovered_cumulative\" FROM \"summary_worldometers_country_86400\" WHERE (\"country\" = 'UK') AND $timeFilter",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "UK" }
     ]
    },
    {
     "alias": "Iran",
     "measurement": "summary_worldometers_country_86400",
     "query": "SELECT \"confirmed_cumulative\"  - \"death_cumulative\" - \"recovered_cumulative\" FROM \"summary_worldometers_country_86400\" WHERE (\"country\" = 'Iran') AND $timeFilter",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Iran" }
     ]
    },
    {
     "alias": "South Korea",
     "measurement": "summary_worldometers_country_86400",
     "query": "SELECT \"confirmed_cumulative\"  - \"death_cumulative\" - \"recovered_cumulative\" FROM \"summary_worldometers_country_86400\" WHERE (\"country\" = 'South Korea') AND $timeFilter",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "South Korea" }
     ]
    },
    {
     "alias": "China",
     "measurement": "summary_worldometers_country_86400",
     "query": "SELECT \"confirmed_cumulative\"  - \"death_cumulative\" - \"recovered_cumulative\" FROM \"summary_worldometers_country_86400\" WHERE (\"country\" = 'China') AND $timeFilter",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "China" }
     ]
    },
    {
     "alias": "USA",
     "measurement": "summary_worldometers_country_86400",
     "query": "SELECT \"confirmed_cumulative\"  - \"death_cumulative\" - \"recovered_cumulative\" FROM \"summary_worldometers_country_86400\" WHERE (\"country\" = 'USA') AND $timeFilter",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "USA" }
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "China" }
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "worldometers",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Italy" }
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "worldometers",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Iran" }
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "worldometers",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Spain" }
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "worldometers",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Germany" }
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "worldometers",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "France" }
     ]
    }
   ]
  },
  {
   "title": "Contagions Active",
   "type": "graph",
   "gridPos": { "h": 14, "w": 10, "x": 10, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "World" }
   ],
   "targets": [
    {
     "alias": "China",
     "measurement": "summary_worldometers_country_86400",
     "query": "SELECT \"confirmed_cumulative\"  - \"death_cumulative\" - \"recovered_cumulative\" FROM \"summary_worldometers_country_86400\" WHERE (\"country\" = 'China') AND $timeFilter",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "China" }
     ]
    },
    {
     "alias": "Outside China",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "summary_worldometers_country_86400",
     "query": "SELECT sum(\"confirmed_cumulative\") - sum(\"recovered_cumulative\") - sum(\"death_cumulative\") FROM \"summary_worldometers_country_86400\" WHERE (\"country\" != 'China') AND $timeFilter GROUP BY time($interval) fill(linear)",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [
         "- \"recovered_cumulative\""
        ],
        "type": "math"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "!=", "value": "China" }
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "worldometers",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "USA" },
      { "condition": "OR", "key": "country", "operator": "=", "value": "U.S." },
      { "condition": "OR", "key": "country", "operator": "=", "value": "United States" }
     ]
    }
   ]
  },
  {
   "title": "Contagions \\ Day",
   "type": "graph",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "World" }
   ],
   "targets": [
    {
     "alias": "Italy",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "confirmed_diff" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Italy" }
     ]
    },
    {
     "alias": "Spain",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "confirmed_diff" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Spain" }
     ]
    },
    {
     "alias": "France",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "confirmed_diff" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "France" }
     ]
    },
    {
     "alias": "Germany",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "confirmed_diff" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Germany" }
     ]
    },
    {
     "alias": "USA",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "confirmed_diff" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "USA" }
     ]
    },
    {
     "alias": "UK",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "confirmed_diff" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "UK" }
     ]
    },
    {
     "alias": "South Korea",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "confirmed_diff" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "South Korea" }
     ]
    },
    {
     "alias": "Iran",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "confirmed_diff" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Iran" }
     ]
    },
    {
     "alias": "South Korea",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "confirmed_diff" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "South Korea" }
     ]
    },
    {
     "alias": "China",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "confirmed_diff" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "China" }
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "worldometers",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "UK" },
      { "condition": "OR", "key": "country", "operator": "=", "value": "United Kingdom" },
      { "condition": "OR", "key": "country", "operator": "=", "value": "U.K." },
      { "condition": "OR", "key": "country", "operator": "=", "value": "UK" }
     ]
    }
   ]
  },
  {
   "title": "Info",
   "type": "text",
   "description": "Covid19",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 16 },
   "content": "###### **Covid19 Data Miner & Dashboard**\n- Open source: [Download](https://github.com/gdassori/covid19_data_miner) \n- Data: [Worldometers.info](https://github.com/gdassori/covid19_data)\n\n\n\n",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Contagions Cumulative",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "World" }
   ],
   "targets": [
    {
     "alias": "Italy",
     "measurement": "summary_worldometers_country_86400",
     "query": "SELECT \"confirmed_cumulative\"  / 100 FROM \"summary_worldometers_country_86400\" WHERE (\"country\" = 'Italy') AND $timeFilter",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Italy" }
     ]
    },
    {
     "alias": "Spain",
     "measurement": "summary_worldometers_country_86400",
     "query": "SELECT (\"confirmed_cumulative\" - \"death_cumulative\" - \"recovered_cumulative\") FROM \"summary_worldometers_country_86400\" WHERE (\"country\" = 'Spain') AND $timeFilter",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Spain" }
     ]
    },
    {
     "alias": "France",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "France" }
     ]
    },
    {
     "alias": "Germany",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Germany" }
     ]
    },
    {
     "alias": "USA",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "USA" }
     ]
    },
    {
     "alias": "UK",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "UK" }
     ]
    },
    {
     "alias": "South Korea",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "South Korea" }
     ]
    },
    {
     "alias": "Iran",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Iran" }
     ]
    },
    {
     "alias": "South Korea",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "South Korea" }
     ]
    },
    {
     "alias": "China",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "China" }
     ]
    }
   ]
  },
  {
   "title": "Deaths Cumulative",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Italy",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "death_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Italy" }
     ]
    },
    {
     "alias": "Spain",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "death_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Spain" }
     ]
    },
    {
     "alias": "France",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "death_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "France" }
     ]
    },
    {
     "alias": "Germany",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "death_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Germany" }
     ]
    },
    {
     "alias": "USA",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "death_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "USA" }
     ]
    },
    {
     "alias": "UK",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "death_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "UK" }
     ]
    },
    {
     "alias": "South Korea",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "death_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "South Korea" }
     ]
    },
    {
     "alias": "Iran",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "death_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Iran" }
     ]
    },
    {
     "alias": "South Korea",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "death_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "South Korea" }
     ]
    },
    {
     "alias": "China",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "death_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "China" }
     ]
    }
   ]
  },
  {
   "title": "Deaths \\ Day",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Italy",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "death_diff" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Italy" }
     ]
    },
    {
     "alias": "Spain",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "death_diff" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Spain" }
     ]
    },
    {
     "alias": "France",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "death_diff" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "France" }
     ]
    },
    {
     "alias": "Germany",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "death_diff" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Germany" }
     ]
    },
    {
     "alias": "USA",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "death_diff" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "USA" }
     ]
    },
    {
     "alias": "UK",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "death_diff" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "UK" }
     ]
    },
    {
     "alias": "South Korea",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "death_diff" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "South Korea" }
     ]
    },
    {
     "alias": "China",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "death_diff" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "China" }
     ]
    },
    {
     "alias": "Iran",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "death_diff" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Iran" }
     ]
    },
    {
     "alias": "South Korea",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "death_diff" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "South Korea" }
     ]
    }
   ]
  },
  {
   "title": "Severes Now",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short", "label": "World" }
   ],
   "targets": [
    {
     "alias": "Italy",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "severe_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Italy" }
     ]
    },
    {
     "alias": "Spain",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "severe_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Spain" }
     ]
    },
    {
     "alias": "France",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "severe_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "France" }
     ]
    },
    {
     "alias": "Germany",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "severe_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Germany" }
     ]
    },
    {
     "alias": "USA",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "severe_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "USA" }
     ]
    },
    {
     "alias": "UK",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "severe_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "UK" }
     ]
    },
    {
     "alias": "South Korea",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "severe_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "South Korea" }
     ]
    },
    {
     "alias": "China",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "severe_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "China" }
     ]
    },
    {
     "alias": "Iran",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "severe_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Iran" }
     ]
    },
    {
     "alias": "South Korea",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "South Korea" }
     ]
    }
   ]
  },
  {
   "title": "Severes \\ Day",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Italy",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "severe_diff" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Italy" }
     ]
    },
    {
     "alias": "Spain",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "severe_diff" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Spain" }
     ]
    },
    {
     "alias": "France",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "severe_diff" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "France" }
     ]
    },
    {
     "alias": "Germany",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "severe_diff" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Germany" }
     ]
    },
    {
     "alias": "USA",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "severe_diff" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "USA" }
     ]
    },
    {
     "alias": "UK",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "severe_diff" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "UK" }
     ]
    },
    {
     "alias": "South Korea",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "severe_diff" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "South Korea" }
     ]
    },
    {
     "alias": "Iran",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "severe_diff" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Iran" }
     ]
    }
   ]
  },
  {
   "title": "Italy Severe vs Death",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "none", "label": "Deaths & Severes" }
   ],
   "targets": [
    {
     "alias": "Severe",
     "measurement": "worldometers",
     "select": [
      [
       { "params": [ "severe_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Italy" }
     ]
    },
    {
     "alias": "Death",
     "measurement": "worldometers",
     "select": [
      [
       { "params": [ "death_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Italy" }
     ]
    },
    {
     "alias": "Confirmed",
     "measurement": "worldometers",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Italy" }
     ]
    }
   ]
  },
  {
   "title": "Europe&Japan Vs Italy",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "none", "label": "Others" }
   ],
   "targets": [
    {
     "alias": "UK",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "worldometers",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "U.K." },
      { "condition": "OR", "key": "country", "operator": "=", "value": "UK" },
      { "condition": "OR", "key": "country", "operator": "=", "value": "United Kingdom" }
     ]
    },
    {
     "alias": "Germany",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "worldometers",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Germany" }
     ]
    },
    {
     "alias": "France",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "worldometers",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "France" }
     ]
    },
    {
     "alias": "Spain",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "worldometers",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Spain" }
     ]
    },
    {
     "alias": "Japan",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "worldometers",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Japan" }
     ]
    },
    {
     "alias": "Italy",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "worldometers",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Italy" }
     ]
    }
   ]
  },
  {
   "title": "Brazil",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Confirmed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Brazil" }
     ]
    },
    {
     "alias": "Recovers",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "recovered_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Brazil" }
     ]
    },
    {
     "alias": "Deaths",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "death_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Brazil" }
     ]
    }
   ]
  },
  {
   "title": "USA",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Severe",
     "measurement": "worldometers",
     "select": [
      [
       { "params": [ "severe_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "USA" }
     ]
    },
    {
     "alias": "Death",
     "measurement": "worldometers",
     "select": [
      [
       { "params": [ "death_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "USA" }
     ]
    },
    {
     "alias": "Confirmed",
     "measurement": "worldometers",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "USA" }
     ]
    }
   ]
  },
  {
   "title": "China",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Confirmed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "worldometers",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "China" }
     ]
    },
    {
     "alias": "Recovers",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "worldometers",
     "select": [
      [
       { "params": [ "recovered_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "China" }
     ]
    },
    {
     "alias": "Deaths",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "worldometers",
     "select": [
      [
       { "params": [ "death_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "China" }
     ]
    }
   ]
  },
  {
   "title": "Top 3 outside outside China",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Italy",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Italy" }
     ]
    },
    {
     "alias": "Iran",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Iran" }
     ]
    },
    {
     "alias": "S.Korea",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "S. Korea" },
      { "condition": "OR", "key": "country", "operator": "=", "value": "South Korea" }
     ]
    }
   ]
  },
  {
   "title": "China Lag",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 87 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Daily detected -9days",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "confirmed_diff" ], "type": "field" },
       { "params": [ "shift_9_days" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "China" }
     ]
    },
    {
     "alias": "Daily ICU Today",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "severe_diff" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "China" },
      { "condition": "AND", "key": "severe_diff", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Italy detected vs ICU",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Daily detected -9days",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "confirmed_diff" ], "type": "field" },
       { "params": [ "shift_9_days" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Italy" }
     ]
    },
    {
     "alias": "Daily ICU Today",
     "measurement": "summary_worldometers_country_86400",
     "select": [
      [
       { "params": [ "severe_diff" ], "type": "field" },
       { "params": [ "hhh" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Italy" },
      { "condition": "AND", "key": "severe_diff", "operator": ">", "value": "0" }
     ]
    }
   ]
  }
 ]
}