{
 "title": "Inspect country",
 "description": "Inspect country",
 "time": { "from": "now-30d", "to": "now+1d" },
 "templating": {
  "list": [
   { "name": "measurement", "label": "measurement", "query": "show measurements" },
   {
    "name": "region",
    "label": "region",
    "query": "select distinct(region) from (select region, confirmed_cumulative from /^$measurement$/) ;"
   }
  ]
 },
 "panels": [
  {
   "title": "Detected",
   "type": "stat",
   "description": "Total detected",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "measurement": "/^$measurement$/",
     "query": "SELECT \"confirmed_cumulative\" FROM /^$measurement$/ WHERE (\"region\" =~ /^$region$/) ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    }
   ]
  },
  {
   "title": "Quote / Detected",
   "type": "stat",
   "description": "Quote",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "worldometers",
     "query": "select sum(b) / sum(a) * 100 from (select a, b from (select sum(c) as a from (SELECT last(\"confirmed_cumulative\") as c FROM /^$measurement$/ WHERE (\"region\" != 'None') GROUP BY \"region\" order by time desc LIMIT 1) order by time desc), (SELECT \"confirmed_cumulative\" as b FROM /^$measurement$/ WHERE (\"region\" =~ /^$region$/) ORDER BY time DESC LIMIT 1) order by time desc) order by time desc;",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "Deaths",
   "type": "stat",
   "description": "Deaths \\ Contagions * 100",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "worldometers",
     "query": "SELECT \"death_cumulative\" FROM /^$measurement$/ WHERE (\"region\" =~ /^$region$/) ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "Deaths",
   "type": "stat",
   "description": "Deaths \\ Contagions * 100",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "worldometers",
     "query": "SELECT 100*\"death_cumulative\" / \"confirmed_cumulative\"  FROM /^$measurement$/ WHERE (\"region\" =~ /^$region$/) ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "Recovered",
   "type": "stat",
   "description": "Deaths \\ Contagions * 100",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "worldometers",
     "query": "SELECT \"recovered_cumulative\"  FROM /^$measurement$/ WHERE (\"region\" =~ /^$region$/) ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "Recovered",
   "type": "stat",
   "description": "Deaths \\ Contagions * 100",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "worldometers",
     "query": "SELECT 100*\"recovered_cumulative\" / \"confirmed_cumulative\"  FROM /^$measurement$/ WHERE (\"region\" =~ /^$region$/)  ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "Active",
   "type": "stat",
   "description": "Total detected",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "worldometers",
     "query": "SELECT \"confirmed_cumulative\" - \"death_cumulative\" - \"recovered_cumulative\"  FROM /^$measurement$/ WHERE (\"region\" =~ /^$region$/)  ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "I.C.U.",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "worldometers",
     "query": "SELECT \"severe_cumulative\"  FROM /^$measurement$/ WHERE (\"region\" =~ /^$region$/)  ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "I.C.U.",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "worldometers",
     "query": "select 100* mean(a) / mean(b) from (SELECT \"severe_cumulative\" as a  FROM /^$measurement$/ WHERE (\"region\" =~ /^$region$/)  ORDER BY time DESC LIMIT 1), (SELECT (\"confirmed_cumulative\" - \"death_cumulative\" - \"recovered_cumulative\") as b  FROM /^$measurement$/ WHERE (\"region\" =~ /^$region$/) ORDER BY time DESC LIMIT 1) order by time desc;\n",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Tests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "worldometers",
     "query": "SELECT last(\"tests_cumulative\") as c FROM /^$measurement$/ WHERE (\"region\" =~ /^$region$/) GROUP BY \"region\" order by time desc LIMIT 1",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "Detection Rate (High is bad)",
   "type": "stat",
   "description": "Why \"High is bad\" ? \nWe have seen that a decent detection rate is ~10%. An high rate may means that testing is very targeted on symptomatic people. This should come with an high ICU rate.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "worldometers",
     "query": "select sum(b) / sum(a) * 100 from (select a, b from (select sum(c) as a from (SELECT last(\"tests_cumulative\") as c FROM /^$measurement$/ WHERE (\"region\" =~ /^$region$/) GROUP BY \"region\" order by time desc LIMIT 1) order by time desc), (SELECT \"confirmed_cumulative\" as b FROM /^$measurement$/ WHERE (\"region\" =~ /^$region$/) ORDER BY time DESC LIMIT 1) order by time desc) order by time desc;",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "Recovered",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Recovered Total",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "recovered_cumulative" ], "type": "field" },
       { "params": [ "Severe" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    },
    {
     "alias": "Recovered Today",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "recovered_diff" ], "type": "field" },
       { "params": [ "Severe" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    }
   ]
  },
  {
   "title": "Deaths",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Death Total",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "death_cumulative" ], "type": "field" },
       { "params": [ "Severe" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    },
    {
     "alias": "Death Today",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "death_diff" ], "type": "field" },
       { "params": [ "Severe" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    },
    {
     "alias": "_",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "recovered_cumulative" ], "type": "field" },
       { "params": [ "Severe" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    }
   ]
  },
  {
   "title": "Status",
   "type": "graph",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "ICU",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "severe_diff" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    },
    {
     "alias": "Death",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "death_diff" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    }
   ]
  },
  {
   "title": "Data",
   "type": "table",
   "gridPos": { "h": 19, "w": 13, "x": 11, "y": 12 },
   "targets": [
    {
     "alias": "Confirmed Total",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       { "params": [ "Severe" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    },
    {
     "alias": "Confirmed Incr.",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "confirmed_diff" ], "type": "field" },
       { "params": [ "Severe" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    },
    {
     "alias": "Severe Active",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "severe_cumulative" ], "type": "field" },
       { "params": [ "Severe" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    },
    {
     "alias": "Severe Today",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "severe_diff" ], "type": "field" },
       { "params": [ "Severe" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    },
    {
     "alias": "Total Death",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "death_cumulative" ], "type": "field" },
       { "params": [ "Severe" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    },
    {
     "alias": "Death Today",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "death_diff" ], "type": "field" },
       { "params": [ "Severe" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    },
    {
     "alias": "Total tests",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "tests_cumulative" ], "type": "field" },
       { "params": [ "Severe" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    },
    {
     "alias": "Tests today",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "tests_diff" ], "type": "field" },
       { "params": [ "Severe" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    }
   ]
  },
  {
   "title": "Contagions w/ 3% CFR",
   "type": "graph",
   "description": "Projection w/ a 3% let.",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Confirmed Total",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       { "params": [ "Severe" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    },
    {
     "alias": "Confirmed Incr.",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "confirmed_diff" ], "type": "field" },
       { "params": [ "Severe" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    },
    {
     "alias": "Conf w/Let.3%",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "death_cumulative" ], "type": "field" },
       { "params": [ "*33.3" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    }
   ]
  },
  {
   "title": "Severe",
   "type": "graph",
   "gridPos": { "h": 13, "w": 11, "x": 11, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Severe Total",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "severe_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    },
    {
     "alias": "Severe Today",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "severe_diff" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    },
    {
     "alias": "3% death rate to severes ~10%",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "death_cumulative" ], "type": "field" },
       { "params": [ "*33.3 * 0.03" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    }
   ]
  },
  {
   "title": "Contagions w/ 1% CFR VS Detected",
   "type": "graph",
   "description": "Projection w/ a 3% let.",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Confirmed Total",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       { "params": [ "Severe" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    },
    {
     "alias": "Confirmed Incr.",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "confirmed_diff" ], "type": "field" },
       { "params": [ "Severe" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    },
    {
     "alias": "Conf w/Let.1%",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "death_cumulative" ], "type": "field" },
       { "params": [ "*100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 44 },
   "content": "<img src=\"//www.shinystat.com/cgi-bin/shinystat.cgi?USER=gdax\" alt=\"Users\" style=\"border:0px\" /></a>\n\n\n\n\n"
  }
 ]
}