{
 "title": "Inspect country",
 "description": "Inspect country",
 "time": { "from": "now-21d", "to": "now+1d" },
 "templating": {
  "list": [
   { "name": "measurement", "label": "measurement", "query": "show measurements" },
   {
    "name": "country",
    "label": "Country",
    "query": "select distinct(country) from (select country, confirmed_cumulative as c from /^$measurement$/) ;"
   },
   {
    "name": "region",
    "label": "region",
    "query": "select distinct(region) from (select region, confirmed_cumulative as c from /^$measurement$/) ;"
   }
  ]
 },
 "panels": [
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 0 },
   "content": "\n<h1><center>Region\\State: $region</center></h1>\n\n\n\n"
  },
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "content": "\n<h1><center>Country: $country</center></h1>\n\n\n\n"
  },
  {
   "title": "Detected",
   "type": "stat",
   "description": "Total detected",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "targets": [
    {
     "measurement": "/^$measurement$/",
     "query": "SELECT \"confirmed_cumulative\" FROM /^$measurement$/ WHERE (\"region\" =~ /^$region$/) ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    }
   ]
  },
  {
   "title": "Quote / Detected",
   "type": "stat",
   "description": "Quote",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "worldometers",
     "query": "select sum(b) / sum(a) * 100 from (select a, b from (select sum(c) as a from (SELECT last(\"confirmed_cumulative\") as c FROM /^$measurement$/ WHERE (\"region\" != 'None') GROUP BY \"region\" order by time desc LIMIT 1) order by time desc), (SELECT \"confirmed_cumulative\" as b FROM /^$measurement$/ WHERE (\"region\" =~ /^$region$/) ORDER BY time DESC LIMIT 1) order by time desc) order by time desc;",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "I.C.U.",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "worldometers",
     "query": "SELECT \"severe_cumulative\"  FROM /^$measurement$/ WHERE (\"region\" =~ /^$region$/)  ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "I.C.U.",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "worldometers",
     "query": "select 100* mean(a) / mean(b) from (SELECT \"severe_cumulative\" as a  FROM /^$measurement$/ WHERE (\"region\" =~ /^$region$/)  ORDER BY time DESC LIMIT 1), (SELECT (\"confirmed_cumulative\" - \"death_cumulative\" - \"recovered_cumulative\") as b  FROM /^$measurement$/ WHERE (\"region\" =~ /^$region$/) ORDER BY time DESC LIMIT 1) order by time desc;\n",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "Detected",
   "type": "stat",
   "description": "Total detected",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "region" ], "type": "tag" }
     ],
     "measurement": "/^$measurement$/",
     "query": "select sum(*) from (SELECT last(\"confirmed_cumulative\") FROM \"autogen\"./^$measurement$/ WHERE (\"country\" =~ /^$country$/) AND $timeFilter GROUP BY \"region\") ",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "ICU $country",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "region" ], "type": "tag" }
     ],
     "measurement": "/^$measurement$/",
     "query": "select sum(*) from (SELECT last(\"severe_cumulative\") FROM \"autogen\"./^$measurement$/ WHERE (\"country\" =~ /^$country$/) AND $timeFilter GROUP BY \"region\") ",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "I.C.U.",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "worldometers",
     "query": "select 100* mean(a) / mean(b) from (SELECT \"severe_cumulative\" as a  FROM /^$measurement$/ WHERE (\"region\" =~ /^$region$/)  ORDER BY time DESC LIMIT 1), (SELECT (\"confirmed_cumulative\" - \"death_cumulative\" - \"recovered_cumulative\") as b  FROM /^$measurement$/ WHERE (\"region\" =~ /^$region$/) ORDER BY time DESC LIMIT 1) order by time desc;\n",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Tests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "worldometers",
     "query": "SELECT last(\"tests_cumulative\") as c FROM /^$measurement$/ WHERE (\"region\" =~ /^$region$/) GROUP BY \"region\" order by time desc LIMIT 1",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "Detection Rate (High is bad)",
   "type": "stat",
   "description": "Why \"High is bad\" ? \nWe have seen that a decent detection rate is ~10%. An high rate may means that testing is very targeted on symptomatic people. This should come with an high ICU rate.",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "worldometers",
     "query": "select sum(b) / sum(a) * 100 from (select a, b from (select sum(c) as a from (SELECT last(\"tests_cumulative\") as c FROM /^$measurement$/ WHERE (\"region\" =~ /^$region$/) GROUP BY \"region\" order by time desc LIMIT 1) order by time desc), (SELECT \"confirmed_cumulative\" as b FROM /^$measurement$/ WHERE (\"region\" =~ /^$region$/) ORDER BY time DESC LIMIT 1) order by time desc) order by time desc;",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "Deaths",
   "type": "stat",
   "description": "Deaths \\ Contagions * 100",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "worldometers",
     "query": "SELECT \"death_cumulative\" FROM /^$measurement$/ WHERE (\"region\" =~ /^$region$/) ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "Deaths",
   "type": "stat",
   "description": "Deaths \\ Contagions * 100",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "worldometers",
     "query": "SELECT 100*\"death_cumulative\" / \"confirmed_cumulative\"  FROM /^$measurement$/ WHERE (\"region\" =~ /^$region$/) ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "Total tests",
   "type": "stat",
   "description": "Total tests",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "region" ], "type": "tag" }
     ],
     "measurement": "/^$measurement$/",
     "query": "select sum(*) from (SELECT last(\"tests_cumulative\") FROM \"autogen\"./^$measurement$/ WHERE (\"country\" =~ /^$country$/) AND $timeFilter GROUP BY \"region\") ",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "Death $country",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "region" ], "type": "tag" }
     ],
     "measurement": "/^$measurement$/",
     "query": "select sum(*) from (SELECT last(\"death_cumulative\") FROM \"autogen\"./^$measurement$/ WHERE (\"country\" =~ /^$country$/) AND $timeFilter GROUP BY \"region\") ",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "Deaths",
   "type": "stat",
   "description": "Deaths \\ Contagions * 100",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "worldometers",
     "query": "SELECT 100*\"death_cumulative\" / \"confirmed_cumulative\"  FROM /^$measurement$/ WHERE (\"region\" =~ /^$region$/) ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "Active",
   "type": "stat",
   "description": "Total detected",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "worldometers",
     "query": "SELECT \"confirmed_cumulative\" - \"death_cumulative\" - \"recovered_cumulative\"  FROM /^$measurement$/ WHERE (\"region\" =~ /^$region$/)  ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "Recovered",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "worldometers",
     "query": "SELECT \"recovered_cumulative\" FROM /^$measurement$/ WHERE (\"region\" =~ /^$region$/) ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "Recovered",
   "type": "stat",
   "description": "Deaths \\ Contagions * 100",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "worldometers",
     "query": "SELECT 100*\"recovered_cumulative\" / \"confirmed_cumulative\"  FROM /^$measurement$/ WHERE (\"region\" =~ /^$region$/)  ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "Active",
   "type": "stat",
   "description": "Total detected",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "worldometers",
     "query": "select sum(l1) - sum(l2) - sum(l3) from (select last(confirmed_cumulative) as l1, last(death_cumulative) as l2, last(recovered_cumulative) as l3 from  \"autogen\"./^$measurement$/  group by region);",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "Recovered $country",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "region" ], "type": "tag" }
     ],
     "measurement": "/^$measurement$/",
     "query": "select sum(*) from (SELECT last(\"recovered_cumulative\") FROM \"autogen\"./^$measurement$/ WHERE (\"country\" =~ /^$country$/) AND $timeFilter GROUP BY \"region\") ",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "Contagions w/ 1% CFR VS Detected",
   "type": "graph",
   "description": "Projection w/ a 3% let.",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Confirmed Total",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       { "params": [ "Severe" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    },
    {
     "alias": "Confirmed Incr.",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "confirmed_diff" ], "type": "field" },
       { "params": [ "Severe" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    },
    {
     "alias": "Conf w/Let.1%",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "death_cumulative" ], "type": "field" },
       { "params": [ "*100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    }
   ]
  },
  {
   "title": "Confirmed cumulative: $measurement",
   "type": "graph",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "alias": "$tag_region",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "region" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "query": "SELECT mean(\"confirmed_cumulative\") FROM /^$measurement$/ WHERE $timeFilter GROUP BY time($__interval), \"region\" fill(linear)",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Data",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "alias": "Tot. Confirm.",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       { "params": [ "Severe" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    },
    {
     "alias": "Incr. Confirm.",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "confirmed_diff" ], "type": "field" },
       { "params": [ "Severe" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    },
    {
     "alias": "ICU Now",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "severe_cumulative" ], "type": "field" },
       { "params": [ "Severe" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    },
    {
     "alias": "Incr. ICU",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "severe_diff" ], "type": "field" },
       { "params": [ "Severe" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    },
    {
     "alias": "Tot. Deaths",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "death_cumulative" ], "type": "field" },
       { "params": [ "Severe" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    },
    {
     "alias": "Incr. Deaths",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "death_diff" ], "type": "field" },
       { "params": [ "Severe" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    },
    {
     "alias": "Tot. tests",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "tests_cumulative" ], "type": "field" },
       { "params": [ "Severe" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    },
    {
     "alias": "Incr. Tests",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "tests_diff" ], "type": "field" },
       { "params": [ "Severe" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    }
   ]
  },
  {
   "title": "Confirmed cumulative: $measurement",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "alias": "$tag_region",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "region" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "query": "SELECT last(\"confirmed_cumulative\"), last(\"death_cumulative\") FROM /^$measurement$/ WHERE $timeFilter GROUP BY \"region\" fill(linear) limit 1",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Deaths",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Death Total",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "death_cumulative" ], "type": "field" },
       { "params": [ "Severe" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    },
    {
     "alias": "Death Today",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "death_diff" ], "type": "field" },
       { "params": [ "Severe" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    },
    {
     "alias": "_",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "recovered_cumulative" ], "type": "field" },
       { "params": [ "Severe" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    }
   ]
  },
  {
   "title": "Recovered",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Recovered Total",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "recovered_cumulative" ], "type": "field" },
       { "params": [ "Severe" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    },
    {
     "alias": "Recovered Today",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "recovered_diff" ], "type": "field" },
       { "params": [ "Severe" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    }
   ]
  },
  {
   "title": "Status",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "ICU",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "severe_diff" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    },
    {
     "alias": "Death",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "death_diff" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    }
   ]
  },
  {
   "title": "Severe",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Severe Total",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "severe_cumulative" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    },
    {
     "alias": "Severe Today",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "severe_diff" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    },
    {
     "alias": "3% death rate to severes ~10%",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "death_cumulative" ], "type": "field" },
       { "params": [ "*33.3 * 0.03" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    }
   ]
  },
  {
   "title": "Contagions w/ 3% CFR",
   "type": "graph",
   "description": "Projection w/ a 3% let.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Confirmed Total",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "confirmed_cumulative" ], "type": "field" },
       { "params": [ "Severe" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    },
    {
     "alias": "Confirmed Incr.",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "confirmed_diff" ], "type": "field" },
       { "params": [ "Severe" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    },
    {
     "alias": "Conf w/Let.3%",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "death_cumulative" ], "type": "field" },
       { "params": [ "*33.3" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 91 },
   "content": "<img src=\"//www.shinystat.com/cgi-bin/shinystat.cgi?USER=gdax\" alt=\"Users\" style=\"border:0px\" /></a>\n\n\n\n\n"
  }
 ]
}