{
 "title": "Mortalità Istat regioni italiane",
 "time": { "from": "2019-12-31T23:00:00.000Z", "to": "2020-03-20T23:00:00.000Z" },
 "panels": [
  {
   "title": "Mortalità Lombardia Istat",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "2020",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "istat_weekly_death_rate",
     "query": "select t from (SELECT sum(\"total_deaths\") as t FROM \"istat_weekly_death_rate\" WHERE (\"region\" = 'Lombardia') AND $timeFilter GROUP BY time($__interval) fill(none)) where t > 0",
     "select": [
      [
       { "params": [ "total_deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "Lombardia" }
     ]
    },
    {
     "alias": "2019",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "istat_weekly_death_rate",
     "select": [
      [
       { "params": [ "total_deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "shift_1_year" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "Lombardia" }
     ]
    }
   ]
  },
  {
   "title": "Mortalità Veneto Istat",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "2020",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "istat_weekly_death_rate",
     "query": "select t from (SELECT sum(\"total_deaths\") as t FROM \"istat_weekly_death_rate\" WHERE (\"region\" = 'Veneto') AND $timeFilter GROUP BY time($__interval) fill(none)) where t > 0",
     "select": [
      [
       { "params": [ "total_deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "Lombardia" }
     ]
    },
    {
     "alias": "2019",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "istat_weekly_death_rate",
     "select": [
      [
       { "params": [ "total_deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "shift_1_year" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "Veneto" }
     ]
    }
   ]
  },
  {
   "title": "Mortalità Lazio Istat",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "2020",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "istat_weekly_death_rate",
     "query": "select t from (SELECT sum(\"total_deaths\") as t FROM \"istat_weekly_death_rate\" WHERE (\"region\" = 'Lazio') AND $timeFilter GROUP BY time($__interval) fill(none)) where t > 0",
     "select": [
      [
       { "params": [ "total_deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "Lombardia" }
     ]
    },
    {
     "alias": "2019",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "istat_weekly_death_rate",
     "select": [
      [
       { "params": [ "total_deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "shift_1_year" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "Lazio" }
     ]
    }
   ]
  },
  {
   "title": "Mortalità Marche Istat",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "2020",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "istat_weekly_death_rate",
     "query": "select t from (SELECT sum(\"total_deaths\") as t FROM \"istat_weekly_death_rate\" WHERE (\"region\" = 'Marche') AND $timeFilter GROUP BY time($__interval) fill(none)) where t > 0",
     "select": [
      [
       { "params": [ "total_deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "Lombardia" }
     ]
    },
    {
     "alias": "2019",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "istat_weekly_death_rate",
     "select": [
      [
       { "params": [ "total_deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "shift_1_year" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "Marche" }
     ]
    }
   ]
  },
  {
   "title": "Mortalità Piemonte Istat",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "2020",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "istat_weekly_death_rate",
     "query": "select t from (SELECT sum(\"total_deaths\") as t FROM \"istat_weekly_death_rate\" WHERE (\"region\" = 'Piemonte') AND $timeFilter GROUP BY time($__interval) fill(none)) where t > 0",
     "select": [
      [
       { "params": [ "total_deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "Lombardia" }
     ]
    },
    {
     "alias": "2019",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "istat_weekly_death_rate",
     "select": [
      [
       { "params": [ "total_deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "shift_1_year" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "Emilia-Romagna" }
     ]
    }
   ]
  },
  {
   "title": "Mortalità Toscana Istat",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "2020",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "istat_weekly_death_rate",
     "query": "select t from (SELECT sum(\"total_deaths\") as t FROM \"istat_weekly_death_rate\" WHERE (\"region\" = 'Toscana') AND $timeFilter GROUP BY time($__interval) fill(none)) where t > 0",
     "select": [
      [
       { "params": [ "total_deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "Lombardia" }
     ]
    },
    {
     "alias": "2019",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "istat_weekly_death_rate",
     "select": [
      [
       { "params": [ "total_deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "shift_1_year" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "Toscana" }
     ]
    }
   ]
  }
 ]
}